### ISSUE TITLE
Close and dismiss in random mode is not working

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/BAM#43]
I can dismiss random announcement but after refreshing the page it is displayed back again... my period is set to 30 days.

![image](https://user-images.githubusercontent.com/778890/75608600-3de90e00-5b01-11ea-822a-262b998d146d.png)

**Comment by Darth-Apple** [comment]
Well, confusingly enough, it's specifically set to do that. There's a setting to completely disable random mode dismissals ("Enable Random Mode announcements to Be Dismissed"). I ended up doing that because automatically refreshing announcements would act a little funny if they were set to be fully dismissed every time. (Does it just dismiss that one announcement and prevent it from displaying again? Does it prevent automatically refreshing announcements from ever displaying again, etc.)

I'm going to do a 2.1 release within about a month and that's on the list of things to try to address. Right now, some of the ideas I had before would happen to generate a lot of queries for users (which I would prefer to avoid), so I'm looking for a more optimized solution for how dismissals should be handled. 

Of course, I can also make random mode announcements completely disappear (meaning no random mode announcement will ever be displayed again) when dismissed. I avoid that primarily because, on my own forum, I found it to a be a little clunky, so I figured it would be for other users as well. But if people want that functionality, I'll add it. :)

I can say that, in testing, this solution brought its own issues. Random mode has been a pain since day one to try to integrate properly with everything else (random mode was actually a carryover from the original BAM that was made long before it was ever released). Still trying to fully address everything and make it up-to-par with everything else!
